# Generated by Django 5.2.7 on 2025-11-14 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use subsubcategory instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Sales.productgroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(blank=True, help_text='Product group - optional grouping within subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Sales.subsubcategory'),
        ),
    ]
