# Generated by Django 5.2.7 on 2025-11-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_product_group_alter_product_subsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_supplied',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='supply_status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='mode_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Mpesa', 'Mpesa'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=20),
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_supplied', models.IntegerField(default=0)),
                ('supply_status', models.CharField(choices=[('Supplied', 'Supplied'), ('Partially Supplied', 'Partially Supplied'), ('Not Supplied', 'Not Supplied')], default='Supplied', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='Sales.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='Sales.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
