# Generated by Django 5.2.7 on 2025-11-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_remove_sale_product_remove_sale_quantity_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
