# Generated by Django 5.2.7 on 2025-11-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_remove_customer_address_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lpo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lpo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lpo',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='recorded_by',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Stock Edit', 'Stock Edit'), ('Sale Created', 'Sale Created'), ('Sale Updated', 'Sale Updated'), ('Supply Update', 'Supply Update')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='LPO',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
