# Generated by Django 5.2.7 on 2025-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_alter_product_minimum_stock_alter_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all products (before VAT)', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='16% VAT on subtotal', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by customer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total - Amount Paid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal + VAT', max_digits=12),
        ),
    ]
