# Generated by Django 5.2.7 on 2026-01-22 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_sale_subtotal_sale_vat_amount_alter_sale_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'verbose_name_plural': 'Stock Entries (Legacy)'},
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('reason', models.CharField(choices=[('RESTOCK', 'Restocking from Supplier'), ('ADJUSTMENT', 'Manual Stock Adjustment'), ('INITIAL', 'Initial Stock Entry'), ('RETURN', 'Customer Return'), ('SALE', 'Sale/Delivery'), ('DAMAGE', 'Damaged/Lost Stock'), ('TRANSFER', 'Stock Transfer')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='Sales.product')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='Sales.sale')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction', 'reason'], name='Sales_stock_directi_ce5c2f_idx'), models.Index(fields=['product', 'created_at'], name='Sales_stock_product_77ddba_idx')],
            },
        ),
    ]
