# Generated by Django 5.2.7 on 2026-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_sale_approved_at_sale_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
