# Generated by Django 5.2.7 on 2026-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_deliveryrecord_deliverylineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelineitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
