# Generated by Django 5.2.7 on 2026-04-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_alter_salelineitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(blank=True, help_text='The date the sale took place (set by staff at time of recording)', null=True),
        ),
    ]
