# Generated by Django 5.2.7 on 2026-04-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0016_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vat_applied',
            field=models.BooleanField(default=False, help_text='Whether 16% VAT was applied to this sale. Set by admin when approving.'),
        ),
    ]
