# Generated by Django 5.2.7 on 2026-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_sale_vat_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
