# Generated by Django 6.0.4 on 2026-05-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0018_sale_payment_date_sale_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
